version: '3.9'
services:
  stable-diffusion:
    image: stablediffusion
    ports:
      - 8501:8501
    environment:
      - INFERENCE_NUM_THREADS=8
    volumes:
      # - /tmp/cache:/root/.cache
      - /tmp/output:/tmp/output
      # - /tmp/models:/root/models
